//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area
    {
        public Area()
        {
            this.SubStations = new HashSet<SubStation>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int ProvinceId { get; set; }
    
        public virtual Province Province { get; set; }
        public virtual ICollection<SubStation> SubStations { get; set; }

        //Optional -- later -- for tracing
        public DateTime CreatedDate { get; set; }
        public DateTime AlteredDate { get; set; }
        public string IP { get; set; }
    }
}
