//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeterReading
    {
        public int Id { get; set; }
        public System.DateTime ReadingDate { get; set; }
        
        public decimal DayValue { get; set; }
        public decimal PeakValue { get; set; }
        public decimal OffPeakValue { get; set; }
        public decimal CoincidentPeak { get; set; }
        public string Remarks { get; set; }
        
        public DateTime CreatedDate { get; set; }
        public DateTime AlteredDate { get; set; }
        public string IP { get; set; }

        public int MeterId { get; set; }
        public int ReportId { get; set; }
    
        public virtual Meter Meter { get; set; }
        public virtual Report Report { get; set; }
    }
}
